# Generated by Django 4.1.5 on 2023-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-07-04'),
            preserve_default=False,
        ),
    ]
